### ISSUE TITLE
Links in footer not clickable

### ISSUE THREAD

**Issue by lutoma** [hack4vdb/anthill-backend#102]
At least in my version of Chrome, the links in the new footer and some of the ones in the header are not clickable because they're covered by the `#first-viewport` div. Maybe needs some `z-index`-ing.

**Comment by stefan2904** [comment]
And the navigation is not working on mobile (responsive, eingeklappt, lässt sich nicht ausklappen). Tested with Android.

**Comment by c3o** [comment]
Merged into #78
