### ISSUE TITLE
Invite logic

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#19]
Minimum, we need a link to share event X from user Y
- Output that link in the invite template
- Link goes to front page but triggers a short extra "You've been invited" text there
- After signup, make sure the event you've been invited to is displayed first even if it shouldn't be there by distance/etc. (unless it's passed, in which case proceed as normal, maybe show a notice if it's easy to do.)

**Comment by benfreu** [comment]
Could we maybe link directly to a meet up detail page?

**Comment by c3o** [comment]
And then capture user email later? Trickier to build.
Invites should always already include all the basic meetup data (it's not much!), so looking at these again in another layout is unlikely to convince you more effecively to follow through than the call to emotion of the front page with a "join your friend here" message would, right?

**Comment by benfreu** [comment]
Nono, it would be guarded by login_required and prompt for user's email and PLZ as part of our special login/signup process

**Comment by benfreu** [comment]
So, basically exactly what you wrote :)

**Comment by c3o** [comment]
Ah you're just talking about the URL or route then? :) for that I'd love to have a short url to hide the 2 Params (fromUserId, toEventId)

**Comment by c3o** [comment]
(Eventually)

**Comment by PeterTheOne** [comment]
This is done, I think.

**Comment by benfreu** [comment]
IMO for the release we should not just fwd the user to the homepage but add a text that they've been invited to meetup X or add another form altogether that contains plz, email, name

**Comment by c3o** [comment]
Invite link currently points at join_meetup ("please enter your name") contrary to the discussion in this issue/thread. Don't think that's optimal user experience.

**Comment by c3o** [comment]
Implemented now as I described in 0f3e62f6a645cf604c425923a561fda200ae0702
Feel free to refactor/change flow, but closing for now :P
