### ISSUE TITLE
User Import

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#20]
- Wir haben eine IMAP Mailbox, Zugangsdaten bei c3o
- Periodisch checken, neue E-Mails darin parsen (Format bei c3o) / evtl working Code+Vagrant von @hex2a vorhanden
- In unsere Datenbank werfen (pro record ein modell instanzieren und save)

TODO HOW TO DEAL WITH THE FACT THAT THESE HAVEN'T BEEN OPTED IN
- Option 1: Ignore, start sending anyway
- Option 2: Scrap all this and create a Django endpoint for Armin/admin to periodically upload a manually exported CSV
- > Create all users from the CSV whose email we didn't already have in our db
- > Send the new ones nice intro mails (events embedded)

**Comment by hex2a** [comment]
IMAP import liegt in "anthill/management/commands/imapimport.py", kann mit "python manage.py importimap" aufgerufen werden, ist aber noch nicht fertig

TODO:
- mail felder ->  model/API (vorname -> first_name)
- Anbindung an die API/model? (validiert die API zusätzlich PLZ,oÄ? wenn nein -> model, wenn ja -> API)
- verschieben von mails in andere IMAP inbox wenn erledigt.

**Comment by c3o** [comment]
We're likely going to go with Option 2

**Comment by c3o** [comment]
Obsoleted by #79
