### ISSUE TITLE
Login UI

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#22]
2 ways to discover login:
- [x] Detect if signup form email is already in DB
- [x] Add small login link to front page: "Bereits bei uns aktiv?" => changes the form to be an obvious email form for a returning user

Needs function that generates login email, displays "pls check your email" message and then quits

**Comment by PeterTheOne** [comment]
#16 is related

**Comment by PeterTheOne** [comment]
#16 is done, there is now a `register_failed.html`.
