### ISSUE TITLE
Invite UI

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#23]
Minimum:
- [x] Link to share

Better:
- [x] Good opengraph info
- [x] Share via FB
- [x] Share via Twitter
- [x] Share via mailto link
- [x] Share via WhatsApp, Messenger, Telegram

Best:
- [ ] Brag publicly (not an invite to a specific event)
- [ ] Tag friends in shares

**Comment by PeterTheOne** [comment]
#16 is related

**Comment by c3o** [comment]
v1 done
