### ISSUE TITLE
Allow chatbot users to create events

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#28]
Since #17 chatbot users can now also "join" suggested (fake) events.

As a result, "join_meetup_bot" (now misnamed) will also need to be able to create address forms for creating these new events. See comment below for how to.

**Comment by benfreu** [comment]
That page should only create user and log them in. Then forward them to join-meetup page with location-id and time-id.

This page should NOT create meet ups so we don't have owner-less fake meet ups in the DB

**Comment by c3o** [comment]
ah right, I learned since typing that that the meetups are only actually created once an address is supplied. should be same here.

**Comment by PeterTheOne** [comment]
`join_meetup_bot` should already correctly forward to `join_meetup`, see: https://github.com/hack4vdb/anthill-backend/commit/ff5e5472ea92c7cee7541427eeaa1f999ea01167 . Please verify by testing this.

**Comment by tosh** [comment]
is the current design decision that the anthill backend will provide the fake events in the API endpoint for the bot (https://weilsumwasgeht.at/api/meetupsbylatlng/47.072331331,15.439072712/)?

this way I don't have to implement the fake event algorithm (meaning it is easy to change in anthill at any time without the bot having to change)?

as far as I understand this would mean that the endpoint (meetups by lat lng) provides both 'real' events (with uuid) and 'fake' events (without uuid). if a bot user wants to join a fake event within the bot i will basically send you the same information just without a uuid so you know you have to actually create the fake event (first user joined)?

lmk if the above is not the case.

**Comment by c3o** [comment]
@tosh As far as I understand but did not verify this was done in #17 as you describe?

**Comment by c3o** [comment]
FYI for the website I made the design decision in b8671431e192ad711445332801ccfa62a0200712 to never show fake events if we have real ones – gotta fill these first and also don't want to provide too much choice. It shouldn't be an endless list but something that suggests you chose A or B or C.

**Comment by c3o** [comment]
Is this done @tosh?

**Comment by benfreu** [comment]
afak, we still don't send fake meetups via the API

**Comment by MSch** [comment]
we now send real and potential meetups, and users can sign up to a potential meetup which creates it.
