### ISSUE TITLE
Show list of user's signed up events

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#31]
List them above the new ones on /meetups

TO SPEC shall we allow cancellation? But then what if you make events unviable by canceling... But otherwise people will just not show up.

**Comment by benfreu** [comment]
Maybe cancel by emailing the campaign?

**Comment by c3o** [comment]
@benfreu Cancel by calling Armin, who will end up upselling you five other meetups.

**Comment by c3o** [comment]
Current solution of displaying "attending" message instead of join button seems good enough for now to me; closing.
