### ISSUE TITLE
Close WebView in Bot after user is done at 'weilsumwasgeht.at'

### ISSUE THREAD

**Issue by tosh** [hack4vdb/anthill-backend#32]
FB Messenger closes the WebView if the user is redirected to the following URL:

`https://www.messenger.com/closeWindow/?image_url=IMAGE_URL&display_text=DISPLAY_TEXT`

According to the FB Messenger documentation `IMAGE_URL` and `DISPLAY_TEXT` will get displayed briefly until the window closes:

https://developers.facebook.com/docs/messenger-platform/send-api-reference/button-template#close_window

**Comment by tosh** [comment]
@benfreu

**Comment by MSch** [comment]
Done
