### ISSUE TITLE
PLZ-to-coordinates broken?

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#34]
Hab mich mit PLZ 1060 registriert und bekam Rottenmann bei Liezen als Vorschlag. In der DB sind meine Koordinaten laut Django Admin in der Mitte Österreichs.

**Comment by PeterTheOne** [comment]
1060 gibts in https://github.com/hack4vdb/anthill-backend/blob/master/anthill/geo/data/plz_latlon.py nicht, Mitte von Österreich ist der Fallback.

**Comment by PeterTheOne** [comment]
Soweit ich es sehe fehlen uns etwa 700 Postleitzahlen. ( https://www.post.at/geschaeftlich_werben_produkte_und_services_adressen_postlexikon.php )

**Comment by PeterTheOne** [comment]
Ich probiere es mal mit http://www.findlatitudeandlongitude.com/batch-geocode/

**Comment by PeterTheOne** [comment]
I haz geodata: https://gist.github.com/PeterTheOne/7135a370b37406e6801d36827e0316cf !

**Comment by PeterTheOne** [comment]
Done https://github.com/hack4vdb/anthill-backend/commit/7e8d7e4468d2d0ed8c5dff0dd8d1cc518c3a9b19
