### ISSUE TITLE
Require only first name attendees

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#36]
Maybe first name is enough? Don't think we use the lastname of non-owners, do we?

**Comment by PeterTheOne** [comment]
First name should be enough, we could even make that a nickname.

**Comment by c3o** [comment]
Prefer first name, then we already have one piece of required data if someone who has attended an event hosts one later. Also I think most of our target market don't have nicknames.

**Comment by c3o** [comment]
@anonjum wants phone number too... I'm afraid it may be a big ask.

**Comment by c3o** [comment]
Done in 1254aa6793c072ee257be2a0f6e7fcfddeb64c68 but without phone for now
