### ISSUE TITLE
emails aren't sent via postmark

### ISSUE THREAD

**Issue by benfreu** [hack4vdb/anthill-backend#39]
@burnoutberni @PeterTheOne @stefan2904

**Comment by c3o** [comment]
SMTP Server smtp.postmarkapp.com
Authenticate with your server API token as both the username and password
Get API token from c3o or MSch or Stefan (he has it in a Slack DM)

**Comment by stefan2904** [comment]
fixed in cbac62fca8f38a1b96df02cc841a813050cf0b6d, sorry for the mistake.
