### ISSUE TITLE
Suggest fewer meetups in Yemen

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#42]
VdB-Fans abroad in allen Ehren, aber ich glaub das ist übertrieben.
https://i.imgur.com/e4QkDIv.png

**Comment by c3o** [comment]
Immerhin gibt es dort an jeder Ecke eine gute Semmeljause...
https://i.imgur.com/H1THXIW.jpg

**Comment by c3o** [comment]
Less snarky: Ich glaub, da werden irgendwo lat & long vertauscht.
(Aber nicht nur bei uns.)

**Comment by PeterTheOne** [comment]
Ich dachte Yemen ist sehr schön um diese Jahrezeit..
