### ISSUE TITLE
four imho crutial functions

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#62]
- sign out must be possible (upper left corner, wherever)
- deregister from event must be possible somewhere (user feels trapped otherwise)
- set up my own event must be possible
- need to see more then three events if they exist -> implement interface with more then one row of events. (cant accept invite for event if i already attend four events)

**Comment by c3o** [comment]
Please don't create duplicate issues or issues that cover multiple unrelated points

1 = #43 
3 = #25

Create the other two as separate issues pls and then close this one
