### ISSUE TITLE
User Interface: see more then three events

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#64]
need to see more then three events if they exist -> implement interface with more then one row of events. (cant accept invite for event if i already attend four events)

**Comment by tosh** [comment]
imho if there are more than 3 events those should be hidden in another page or behind a 'show more' or 'i need other dates where i have time' link

what's the reasoning behind the change?

**Comment by anonjum** [comment]
Need to add navigation between "my events" and "more events"

![bildschirmfoto 2016-08-22 um 00 35 51](https://cloud.githubusercontent.com/assets/21046499/17840227/6c087d5e-6800-11e6-9b75-f827b408ac16.png)
![bildschirmfoto 2016-08-22 um 00 35 58](https://cloud.githubusercontent.com/assets/21046499/17840228/6c0c28dc-6800-11e6-9bf4-efeb7603f2a3.png)

**Comment by MSch** [comment]
Fixed to be according to @c3o's spec from the group call.
