### ISSUE TITLE
Collect every attendee's phone number

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#65]

**Comment by anonjum** [comment]
Needs to have mandatory check box: 

Die Kampagne (später ersetzen durch "der Verein Gemeinsam für Van der Bellen") darf mich im Zusammenhang mit der Bundespräsidentschafts-Kampagne von Alexander Van der Bellen telefonisch kontaktieren, sowie mich über den weiteren Verlauf der Kampagne informiert. 

if user doesnt check this box he cannot participate in event.

**Comment by anonjum** [comment]
Future feature (possible) - second checkbox: I want you to send my number to Tom (organizer) so he can get in touch.
