### ISSUE TITLE
Landing-Page: Add the kleingedruckte

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#68]
![bildschirmfoto 2016-08-21 um 22 50 51](https://cloud.githubusercontent.com/assets/21046499/17839737/cdb28798-67f1-11e6-995a-7d27e32eaf83.png)

Add another line: 
### **Van der Bellen muss gewinnen.**

**Bei dieser Wahl kann ich nicht sitzen bleiben. Ich bin bereit, aktiv zu werden.** 
Die Kampagne darf mich elektronisch kontaktieren.

(maybe in smaller font size?)
will put them at ease regarding legal issues.

**Comment by c3o** [comment]
v1 done in 69e8de09288e84118a7e211e0b755b7d8f477a73
