### ISSUE TITLE
Bug: Facebook Share doesnt work

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#69]
![bildschirmfoto 2016-08-21 um 22 56 50](https://cloud.githubusercontent.com/assets/21046499/17839768/a0619db4-67f2-11e6-8aef-c53690a592f8.png)

This urls: http://weilsumwasgeht.at/invite/4e3ad936-a0c6-460f-b733-92c19965407a
This fb link: https://www.facebook.com/login.php?api_key=1595950890699096&skip_api_login=1&display=popup&cancel_url=http%3A%2F%2Fweilsumwasgeht.at%2Fthankyou%2F4e3ad936-a0c6-460f-b733-92c19965407a&next=https%3A%2F%2Fwww.facebook.com%2Fdialog%2Fsend%3F_path%3Dsend%26app_id%3D1595950890699096%26client_id%3D1595950890699096%26redirect_uri%3Dhttp%253A%252F%252Fweilsumwasgeht.at%252Fthankyou%252F4e3ad936-a0c6-460f-b733-92c19965407a%26display%3Dpopup%26link%3Dhttp%253A%252F%252Fweilsumwasgeht.at%252Fi%252F7995d162d4%252F%26from_login%3D1

I'm Max (max@max.de)

**Comment by c3o** [comment]
Think I fixed it TBC
