### ISSUE TITLE
Design: Set fixed width and height for event.

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#70]
Events are weirdly resizing, breaking and they have different heights depending on state (exists, sugested, "im in"). I'd suggest setting width to 300px and height to 375 px. That way they always align.

![bildschirmfoto 2016-08-21 um 22 58 25](https://cloud.githubusercontent.com/assets/21046499/17839778/f22cfa58-67f2-11e6-96ad-f31c345cd4f1.png)
![bildschirmfoto 2016-08-21 um 22 58 42](https://cloud.githubusercontent.com/assets/21046499/17839777/f22a6edc-67f2-11e6-83ae-096b5b60eccf.png)
![bildschirmfoto 2016-08-21 um 22 58 52](https://cloud.githubusercontent.com/assets/21046499/17839779/f22e268a-67f2-11e6-899e-0dec9db96896.png)

**Comment by MSch** [comment]
This is (partly) an artifact since I'm not yet limiting the output to three events.

**Comment by anonjum** [comment]
I dont Unterstand this. But magicians make good choices. Just wanted to bring it up as I noticed.
