### ISSUE TITLE
Setup static file caching properly

### ISSUE THREAD

**Issue by benfreu** [hack4vdb/anthill-backend#71]
Ad website not properly reloading cached assets automatically: Should probably throw something like this in the settings:
`STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'`
for all the automatic static file versioning goodness (assuming the staticfiles thing is used)

**Comment by MSch** [comment]
I made sure that responses from the Django app don't get cached: https://github.com/hack4vdb/anthill-backend/commit/959a093ee8ce5726ea35abfaec0e2a3d33982553

Not sure about assets, but I hope that nginx is doing something okay. It'll be fine.
