### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#73]
It's in their data protection statement that they use HTTPS when transmitting personal data

**Comment by PeterTheOne** [comment]
As far as I know @stefan2904 did the HTTPS setup for the old domain and disabled this because of development reasons.

**Comment by stefan2904** [comment]
We already support HTTPS.
If you want I can enforce it.

**Comment by stefan2904** [comment]
I added the new domain (tell me if there are multiple) to the cert last week.

The only thing I disabled is enforcing HTTPS, but I can reenable that. (Will break the Map rendering in the admin (fixed in the current, not yet released, Django Version), not sure if we need that.)

**Comment by c3o** [comment]
Yes forcing it seems necessary for the signup form to comply with VdB data protection statement.
Maybe not force it for Django admin? ;D

**Comment by stefan2904** [comment]
done, 
- HSTS enabled für alle domains (d.h. sobald man mal per HTTPS drauf geht verwendet der Browser automatisch nur mehr HTTPS).
- automatisch Weiterleiten von HTTP auf HTTPS derweil nur für die Haupt-Domain
