### ISSUE TITLE
Implement Unsuscribe Link Email 

### ISSUE THREAD

**Issue by anonjum** [hack4vdb/anthill-backend#77]
Disclaimer: Das ist eine automatisch generierte Nachricht, die Du erhältst, weil Du Alexander Van der Bellen unterstützten möchtest und zu diesem Zwecke Deine Daten entweder auf vanderbellen.at oder auf weilsumwasgeht.at hinterlassen hast. Wenn Du keine weiteren Nachrichten mehr von weilsumwasgeht.at erhalten möchtest KLICKE AUF DIESEN LINK. Wenn Du keine Nachrichten mehr von vanderbellen.at mehr erhalten möchtest sende eine Nachricht mit dem Betreff "Daten Löschen" an kontakt@vanderbellen.at

**Comment by c3o** [comment]
Duplicate of #40
