### ISSUE TITLE
Password-protect until launch

### ISSUE THREAD

**Issue by c3o** [hack4vdb/anthill-backend#80]
Simple shared HTTP basic auth in front of the whole thing?

**Comment by anonjum** [comment]
http://wanderlust.i-kiu.at/mitmachen/aktiv-werden/mitmachen/
same thing like here?

**Comment by stefan2904** [comment]
Done.
_Ask in slack (or me) for an account._

**Howto setup:**
  http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html

**Howto add user:**
Create password with `mkpasswd`.
Add user/password to `/etc/nginx/htpasswd`.

**Comment by stefan2904** [comment]
fyi: re-obened /api, otherweise the bot is broken ;-)

**Comment by stefan2904** [comment]
```
    location / {
        try_files $uri @proxy_to_app;

        auth_basic 'anthill demo';
        auth_basic_user_file /etc/nginx/htpasswd;
    }

    location /api/ {
        try_files /api/$uri @proxy_to_app;

        auth_basic off;
    }
```
