### ISSUE TITLE
Secret to authenticate bot requests is in the source

### ISSUE THREAD

**Issue by MSch** [hack4vdb/anthill-backend#87]
[anthill/views.py](https://github.com/hack4vdb/anthill-backend/blob/master/anthill/views.py#L267)

``` python
def join_meetup_fb_messenger(request, signeddata):

    s = JSONWebSignatureSerializer('anthill4vdb')

    indata = s.loads(signeddata)
```

**Comment by stefan2904** [comment]
Move to local config? (If wew change this, it also needs to be change on the bot end. /cc @tosh)

(Same key for the planned protection of other api endpoints, I guess.)

**Comment by tosh** [comment]
Jup we'd need to change this at the same time

**Comment by MSch** [comment]
> (Same key for the planned protection of other api endpoints, I guess.)

Just to make sure: Same secret for all API endpoints used by the bot, but a different secret for the API endpoints exposed to the campaign website

**Comment by stefan2904** [comment]
define "exposed to the campaign website". to a frontend or to the CRM?

**Comment by stefan2904** [comment]
ok, in settings_local, there is now

``` python
BOT_API_KEY = 'key1'
CRM_API_KEY = 'key2'
```

to use:

``` python
from hack4vdb.settings_local import BOT_API_KEY

from itsdangerous import JSONWebSignatureSerializer
s = JSONWebSignatureSerializer(BOT_API_KEY)
```

(ask me for the specific keys or look in the file on the server.)

**Comment by stefan2904** [comment]
@tosh changed on my site, please update bot (see slack for new `BOT_API_KEY`)

**Comment by tosh** [comment]
new bot key live in bot
