### ISSUE TITLE
Signing URL requests between bot and django

### ISSUE THREAD

**Issue by MSch** [hack4vdb/anthill-backend#9]

**Comment by tosh** [comment]
@MSch can we use this:

http://pythonhosted.org/itsdangerous/#json-web-signatures

?

**Comment by tosh** [comment]
http://pythonhosted.org/itsdangerous/#itsdangerous.JSONWebSignatureSerializer

**Comment by MSch** [comment]
Yes that works fine as well 👍

**Comment by c3o** [comment]
Done by 3239fdfd64c2ea8765403ff39f27e2983c4df970
