### ISSUE TITLE
Static Maps = Request to Google

### ISSUE THREAD

**Issue by stefan2904** [hack4vdb/anthill-backend#98]
The static Maps next to the Meetups are loaded from Google. Therefore Google knows you are on the site. Is this an issue?

If so:
Either: remove
Or: Replace with less problematic API
Or: Implement loading via server, cache

Followup: check other external resources.

**Comment by PeterTheOne** [comment]
Also move google API key to settings.

**Comment by lutoma** [comment]
@PeterTheOne Your change seems to have broken the map in the lower area of the /join_meetup/ page, which just seems to request `https://mitmachen.vanderbellen.at/api/staticmaps///` (probably some missing variables in the template)?

**Comment by PeterTheOne** [comment]
@lutoma sollte jetzt wieder gehn.

**Comment by lutoma** [comment]
@PeterTheOne Now I get `https://mitmachen.vanderbellen.at/api/staticmaps/Ottakring//` as URL which also 404s. But maybe it's just the specific event that's broken (https://mitmachen.vanderbellen.at/join_meetup/?datetime=2016-09-03T11:00&location_id=162)

**Comment by PeterTheOne** [comment]
@lutoma this should have fixed the 404 https://github.com/hack4vdb/anthill-backend/commit/a5e59684e9561f62846ff253e58d1317f72a8737#diff-9d38da77220fab881faf29e497ffdaa3R69 ... hmm

**Comment by lutoma** [comment]
@PeterTheOne Changing the regex to `api/staticmaps/(?P<city>[\d\w-]+)/(?P<street>[\d\w\W-]*)?/?` seems to work.

**Comment by PeterTheOne** [comment]
@lutoma PR? ^^°
